### ISSUE TITLE
[Bug] Generate two different blob id when build RAFS Filesystem in Native Mode from a Directory and from a tar.gz File

### ISSUE THREAD

**Issue by zhangshuiyong** [dragonflyoss/image-service#1258]
test branch: stable/v2.2

test datasource: [cifar-10-python.tar.gz](http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz)

when Build RAFS Filesystem in Native Mode from a Directory **VS** from a tar.gz File, the output like the below:

![image](https://user-images.githubusercontent.com/1655233/236155687-b8d2dfed-ac6a-419c-87b5-cf7af3c82b66.png)

**Comment by jiangliu** [comment]
The two blob files generated are valid, there's no `bug` here.
The difference is caused by the order to dump data of files. 
- With `-t dir-rafs`, nydus-image walks directories and proccesses all data files. The order to process files are determined by OS, which is sorted by file name in ascend mode.
- With `-t targz-rafs`, nydus-image walks tar headers in the tar file. The order to process files from tar file is determined by the tar stream, it's sorted by name in descend mode by default.
- We can direct tar to generate tar stream in ascend mode by `tar --sort name`.
- With a tar file generated by `tar --sort name`, `-t targz-rafs` and `-t dir-rafs` generates the same data blob.

On the other hand, the default order given by tar tool is not optimal for nydus, which may cause performance drop to data prefetch. It would be better to dump files from tar in ascend mode, but haven't found an easy way to achieve that yet.
