### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by hhstu** [dragonflyoss/image-service#15]
我看了一些蚂蚁的关于Nydus博客，其中容器镜像按需下载，用户不再需要下载完整镜像就能启动容器。 这句话应该怎么理解？ 比如我有个基于jdk的镜像，jdk是一层，jar包是一层，会在下载完成jdk那一层后就把容器run起来了吗？

**Comment by changweige** [comment]
No. In fact,  you have to make use some kind of tool to convert your OCI image into Nydus/Rafs format. The tool which is named as `nydusify` can also be found in this repo, too. Please refer to `README.md` for trial instructions. Now, it relies on `contianerd`, however, we are planning to get rid of containerd in the soon future. 

After a successful image conversion, you will have two artifacts - *boostrap* and *blob*.

In addition, you can use image builder which is wrapped by `nydusify`  to convert an image with multiple layers  by yourself.
If not for too many layers, it should not be hard.

> 会在下载完成jdk那一层后就把容器run起来了吗？
After the conversion, you don't have seperated jdk layer like the original tar anymore. The only needed thing is `boostrap`.
Enjoy it. :-)

**Comment by imeoer** [comment]
Hi @hhstu , Nydus will split file data in the image layer into multiple chunks (default is 1MB per one), if the application in container request read these data (for example in your case, loading `JDK` runtime or `JAR` package), Nydus will only read from the data chunks of `JDK` or `JAR` on-demand, instead of the whole image layer data chunks.

**Comment by hhstu** [comment]
我会尽量在这周末搞定它的原理，如果搞不定我还会再回来问哈哈哈 @imeoer

**Comment by imeoer** [comment]
@hhstu Here is our slide share on Open Infra Summit 2020, you can find more detail. ;)
https://drive.google.com/file/d/1LRfLUkNxShxxWU7SKjc_50U0N9ZnGIdV/view?usp=sharing

**Comment by hhstu** [comment]
感谢！Thanks @imeoer
