### ISSUE TITLE
Consultation: About Nydus use business scenarios & implementation status

### ISSUE THREAD

**Issue by bengbeng-pp** [dragonflyoss/image-service#492]
In the process of actual implementation, although the image pull time has been accelerated, the time for container startup and business has become longer. I understand that this situation is inevitable. Now ask some practical experience about the official landing to help us implement Nydus on a larger scale.

1. How much influence does the on-demand loading method have on container startup and business startup, and is there any data on this?
2. What is the impact of the on-demand loading method on container startup and business startup? For example, business scenarios, development languages, etc. We expect that based on this data, we will determine the priority and large-scale implementation of Nydus scenarios.
3. In addition, are there any optimization measures or plans for this situation?

**Comment by bergwolf** [comment]
Hi @bengbeng-pp, may I ask at what scale you are looking at implementing Nydus?

As shown on the Nydus website, https://nydus.dev/, we (Ant Group) create millions of containers with Nydus in production every day. Alibaba Cloud and Bytedance are also using Nydus in production on a large scale. Hope it gives you confidence about Nydus's production quality. ;)

W.r.t. your questions, in our production case, with the combination of Dragonfly p2p distribution, image data prefetching, IO amplification, and chunk level deduplication, the impact of on-demand loading is quite negligible. A container always starts very quickly and the business applications start just like their needed data is all local.

When disabling all the above optimizations, the impact of on-demand loading becomes obvious and varies for different container images. Application metadata operation (such as ls, open, readdir, etc.) is still quite fast since with Nydus we have all file system metadata ready locally upon container pulling. Application data read operations OTOH have to suffer from the network latency. But hey, we do recommend that users enable these optimizations in production since there is little reason not to. LOL

If you are interested in knowing more implementation details and meeting more Nydus developers and users, feel free to join our slack or Ding Talk group here (https://github.com/dragonflyoss/image-service#community).

**Comment by bengbeng-pp** [comment]
1. Ding Talk group QR code has expired, https://github.com/dragonflyoss/image-service#community .
2. The cold start in the above figure means that the application starts successfully? Is the data in the picture without the local cache?
3. What does IO amplification refer to, and is there any relevant information?
4. Have Alibaba Cloud and ByteDance landed in online applications?
5. If there is no image data prefetching, will real-time data read affect the business startup and interface performance, because image data prefetching may not be applicable to our scenario, because recording traces may cause the operation of business logic to modify business data.

**Comment by bengbeng-pp** [comment]
May I ask if there are any pain points now, and what will be the next evolution.

**Comment by jiangliu** [comment]
> 5. If there is no image data prefetching, will real-time data read affect the business startup and interface performance, because image data prefetching may not be applicable to our scenario, because recording traces may cause the operation of business logic to modify business data.

Nydus provides several mechanisms to reduce jitter/improve application performance:
1) read amplification, which is something like linux readahead to reduce network QPS.
2) data layout optimization, which puts data  of files accessed by the application to the head of data blobs and prefetches those datum.
3) prefetch a list of files/directories supplied by command line options.
4) full data downloading, which pulls all image data to local in the background if enabled.

**Comment by bengbeng-pp** [comment]
> > 5. If there is no image data prefetching, will real-time data read affect the business startup and interface performance, because image data prefetching may not be applicable to our scenario, because recording traces may cause the operation of business logic to modify business data.
> 
> Nydus provides several mechanisms to reduce jitter/improve application performance:
> 
> 1. read amplification, which is something like linux readahead to reduce network QPS.
> 2. data layout optimization, which puts data  of files accessed by the application to the head of data blobs and prefetches those datum.
> 3. prefetch a list of files/directories supplied by command line options.
> 4. full data downloading, which pulls all image data to local in the background if enabled.

Does the prefetch function need to record the io behavior for a period of time? Does this mean that the application needs to actually run?

**Comment by jiangliu** [comment]
> > > 5. If there is no image data prefetching, will real-time data read affect the business startup and interface performance, because image data prefetching may not be applicable to our scenario, because recording traces may cause the operation of business logic to modify business data.
> > 
> > 
> > Nydus provides several mechanisms to reduce jitter/improve application performance:
> > 
> > 1. read amplification, which is something like linux readahead to reduce network QPS.
> > 2. data layout optimization, which puts data  of files accessed by the application to the head of data blobs and prefetches those datum.
> > 3. prefetch a list of files/directories supplied by command line options.
> > 4. full data downloading, which pulls all image data to local in the background if enabled.
> 
> Does the prefetch function need to record the io behavior for a period of time? Does this mean that the application needs to actually run?

There are two possible way to provide the pattern list for prefetch:
1) run the container for a while and record the accessed files
2) give some common hints according to type of applications in container. For example, there are pattarns for nodejs, python apps.

**Comment by liubogithub** [comment]
No response for 2 weeks, close it for now.
