### ISSUE TITLE
relationship with stargz-snapshotter?

### ISSUE THREAD

**Issue by xunwumizhi** [dragonflyoss/image-service#50]
I feel nydus have the same thinking of  `Stargz Snapshotter` https://github.com/containerd/stargz-snapshotter  about fast the container bootstrap process,  and  stargz-snapshotter also have eStargz image format like nydus's rafs image format.

why setup a new project `Nyus`, not base on the Stargz Snapshotter?  Is there some doc about explain the relationship between `Nydus`  and `Stargz Snapshotter` ?

**Comment by bergwolf** [comment]
Hi @xunwumizhi, we did look into quite a few previous community works (like cernvmfs, slacker, crfs/stargz/estargz, filegrain, umoci etc.) before starting the nydus project. They all share the same goal of speeding up container startup process, and each has different drawbacks here or there.

To explain why not `estargz` in particular, its layered TOC design makes it less optimal because each layer needs to be mounted as a FUSE mountpoint resulting in unnecessary kernel-userspace round trips. There are other minor issues such as lack of uncmopressed chunk size record in the format and the memory footprint of go runtime does not look good in a density container deployment.

OTOH, nydus' `rafs` file system format does share a lot common designs with `estargz`. In fact, nydus even implemented a built-in converter from `stargz` to `rafs` in the nydus snapshotter so that nydus can support `stargz` images as well. The difference is that nydus converts multiple `stargz` TOC layers into a single flat `rafs` bootstap so that a single FUSE mountpoint can be used.

And we do look forward to cooperate with the stargz community when nydus becomes more mature. Especially IMO `rafs` and `stargz` formats can together layout a proper basis for the next generation of the OCI image specification.

**Comment by liubogithub** [comment]
@xunwumizhi Should you have further questions, please reopen the issue, thanks.
