### ISSUE TITLE
Nydusd accesses Dragonfly in a mirror registry fashion

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/image-service#716]
At present, nydusd can only access dragonfly as an HTTP proxy. It has some cons:
1. For HTTPS registry, must provide a copy of CA and private key to dragonfly dfdaemon.
2. Hardly support multiple mirrors
3. An extra HTTP connect is needed (a more round trip)

My proposal is to support accessing dragonfly as a pull-through cache.
To achieve it:
1. add more items to nydusd configuration file:
2. support filling HTTP header according to a configuration JSON file.

```
{
  "device": {
    "backend": {
      "type": "registry",
      "config": {
        "scheme": "http",
        "repo": "nydus",
        "host": "127.0.0.1:8000",
        "mirrors": [{"scheme":"https","host": "dragonfrly.dfdaemon.org:65001", "username": "itsme", "password": "PASS", "header":"X-dragonfaly-header"}]
      }
    },

```

Furthermore, we can try to configure multiple registries to nydusd when it works globally in snapshotter shared mode

**Comment by imeoer** [comment]
As per the offline discussion with @changweige, nydus can integrate dragonfly in two ways, proxy mode and mirror mode.

1. proxy mode integration documentation: https://d7y.io/zh/docs/setup/runtime/containerd/proxy/

For example, for https image registry, we need to configure the https decryption certificate for d7y so that it can cache the blob data, but there is a workaround without configuring the certificate:

- For nydusd, set to `http` scheme for the source image registry.
- For d7y dfdaemon, enable `useHTTPS` option, when d7y dfdaemon intercepts the http request, it will automatically replace the http with https to request the source image registry center, thus eliminating the need to decrypt https.

This workaround needs to take into account fallback, when d7y has down, nydusd needs to fallback to the source image registry of https, this feature still needs to be implemented.

2. mirror mode integration documentation: https://d7y.io/zh/docs/setup/runtime/containerd/mirror

Currently nydus can only support single mirror (d7y fixed configuration mirror url), but not support dynamic multi-mirrors, a feasible design to support multi-mirrors is as follows:

For example, the mirror requirement is:

- `ctr pull A.com` will be mirrored to B.com
- `ctr pull C.com` will be mirrored to D.com

Then when `ctr pull A.com`, the nydus snapshotter should generate the `config.json` file for nydusd like this:

``` json
{
  "device": {
    "backend": {
      "type": "registry",
      "config": {
        "scheme": "https",
        "repo": "library/nginx",
        "host": "A.com",
        "skip_verify": true,
        "mirrors": [
          {
            "scheme": "http",
            "host": "B.com",
            "headers": {
              "X-Dragonfly-Registry": "https://A.com"
            }
          }
        ]
      }
    }
  },
  ...
}
```

Similarly, when `ctr pull C.com`, the generated nydusd config.json is replaced with `"X-Dragonfly-Registry": "https://D.com"`

This means that the nydus snapshotter should have a configuration of:

``` toml
<snapshotter startup arguments... >

<nydusd configuration template... >

[[resolver.host. "A.com".mirrors]]
host = "http://B.com"
headers = "X-Dragonfly-Registry": "https://A.com"
insecure = true

[[resolver.host. "C.com".mirrors]]
host = "D.com"
headers = "X-Dragonfly-Registry": "https://C.com"
insecure = true
```

**Comment by changweige** [comment]
@zyfjeff Is there any progress on this feature, I think it is instrumental when integrating with Dragonlfy.

**Comment by zyfjeff** [comment]
> @zyfjeff Is there any progress on this feature, I think it is instrumental when integrating with Dragonlfy.

Sorry, I haven't implemented it yet, currently, nydus communicates with dragonfly via https, and it just works.

**Comment by changweige** [comment]
> > @zyfjeff Is there any progress on this feature, I think it is instrumental when integrating with Dragonlfy.
> 
> Sorry, I haven't implemented it yet, currently, nydus communicates with dragonfly via https, and it just works.

Thanks for feedback ~

**Comment by changweige** [comment]
@imeoer 

> For nydusd, when the option "use_http": true is enabled, need to use scheme http to request source registry with proxy, and fallback to https if proxy is unhealthy, this feature still needs to be implemented.

I guess you are suggesting use the original HTTP scheme to access the original registry rather than only https?
Registry host can also be configured as HTTP

**Comment by imeoer** [comment]
Refer to https://github.com/containerd/nydus-snapshotter/pull/178

**Comment by changweige** [comment]
Let's close this issue since related PR has been merged into mainline
